# Generated by Django 3.2.5 on 2021-09-16 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20210916_1424'),
        ('students', '0003_logger'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='in_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group.groups'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
