# Generated by Django 3.2.5 on 2021-09-16 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_rename_group_students_groups_group_student'),
        ('students', '0005_alter_student_in_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='in_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group.groups'),
        ),
    ]
