# Generated by Django 3.2.5 on 2021-09-18 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(db_column='Group name', max_length=200, verbose_name='Group Name')),
                ('group_student', models.IntegerField(db_column='Students in group', null=True, verbose_name='Students in group')),
                ('group_curator', models.OneToOneField(db_column='Curator', null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
