# Generated by Django 3.2.5 on 2021-09-18 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='group_headman',
            field=models.OneToOneField(db_column='Headman', null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
