# Generated by Django 3.2.5 on 2021-09-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20210916_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='group_students',
            new_name='group_student',
        ),
    ]
