# Generated by Django 3.2.5 on 2021-09-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_rename_group_students_groups_group_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_name',
            field=models.CharField(db_column='Group name', max_length=200, verbose_name='Group Name'),
        ),
    ]
