# Generated by Django 3.2.5 on 2021-09-16 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('students', '0008_auto_20210916_1732'),
        ('group', '0004_alter_groups_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_curator',
            field=models.OneToOneField(db_column='Curator', null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_headman',
            field=models.OneToOneField(db_column='Headman', null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_student',
            field=models.IntegerField(db_column='Students in group', null=True, verbose_name='Students in group'),
        ),
    ]
